### ISSUE TITLE
chromedriver errors(?)

### ISSUE THREAD

**Issue by Elusv** [obaskly/AiDetectionBypass#2]
Tested with latest update - did get much further, however I got a lot of the blow - presumably for each "chunk".  Seems to kludgy to be a reasonable solution for scale (and small amounts of text adjustment can be done by simple cut-paste).  I removed the gmail connection after testing.

Magic link expired detected in URL: https://undetectable.ai/?error=Verification
Magic link expired. Switching to OTP mode.
Error during OTP handling: Message: 
Stacktrace:
0   chromedriver                        0x0000000104aace82 chromedriver + 6696578
1   chromedriver                        0x0000000104aa4c9a chromedriver + 6663322
2   chromedriver                        0x00000001044ace3e chromedriver + 405054
3   chromedriver                        0x00000001044fd815 chromedriver + 735253
4   chromedriver                        0x00000001044fdd11 chromedriver + 736529
5   chromedriver                        0x0000000104548314 chromedriver + 1041172
6   chromedriver                        0x000000010452289d chromedriver + 886941
7   chromedriver                        0x00000001045453f4 chromedriver + 1029108
8   chromedriver                        0x0000000104522613 chromedriver + 886291
9   chromedriver                        0x00000001044ef950 chromedriver + 678224
10  chromedriver                        0x00000001044f034e chromedriver + 680782
11  chromedriver                        0x0000000104a7a770 chromedriver + 6489968
12  chromedriver                        0x0000000104a7d219 chromedriver + 6500889
13  chromedriver                        0x0000000104a7cd3b chromedriver + 6499643
14  chromedriver                        0x0000000104a7d6a5 chromedriver + 6502053
15  chromedriver                        0x0000000104a65524 chromedriver + 6403364
16  chromedriver                        0x0000000104a7d98f chromedriver + 6502799
17  chromedriver                        0x0000000104a56954 chromedriver + 6342996
18  chromedriver                        0x0000000104a95378 chromedriver + 6599544
19  chromedriver                        0x0000000104a95535 chromedriver + 6599989
20  chromedriver                        0x0000000104aa4868 chromedriver + 6662248
21  libsystem_pthread.dylib             0x00007ff810ffe18b _pthread_start + 99
22  libsystem_pthread.dylib             0x00007ff810ff9ae3 thread_start + 15

Error during sign-in process: Message: 
Stacktrace:
0   chromedriver                        0x0000000104aace82 chromedriver + 6696578
1   chromedriver                        0x0000000104aa4c9a chromedriver + 6663322
2   chromedriver                        0x00000001044ace3e chromedriver + 405054
3   chromedriver                        0x00000001044fd815 chromedriver + 735253
4   chromedriver                        0x00000001044fdd11 chromedriver + 736529
5   chromedriver                        0x0000000104548314 chromedriver + 1041172
6   chromedriver                        0x000000010452289d chromedriver + 886941
7   chromedriver                        0x00000001045453f4 chromedriver + 1029108
8   chromedriver                        0x0000000104522613 chromedriver + 886291
9   chromedriver                        0x00000001044ef950 chromedriver + 678224
10  chromedriver                        0x00000001044f034e chromedriver + 680782
11  chromedriver                        0x0000000104a7a770 chromedriver + 6489968
12  chromedriver                        0x0000000104a7d219 chromedriver + 6500889
13  chromedriver                        0x0000000104a7cd3b chromedriver + 6499643
14  chromedriver                        0x0000000104a7d6a5 chromedriver + 6502053
15  chromedriver                        0x0000000104a65524 chromedriver + 6403364
16  chromedriver                        0x0000000104a7d98f chromedriver + 6502799
17  chromedriver                        0x0000000104a56954 chromedriver + 6342996
18  chromedriver                        0x0000000104a95378 chromedriver + 6599544
19  chromedriver                        0x0000000104a95535 chromedriver + 6599989
20  chromedriver                        0x0000000104aa4868 chromedriver + 6662248
21  libsystem_pthread.dylib             0x00007ff810ffe18b _pthread_start + 99
22  libsystem_pthread.dylib             0x00007ff810ff9ae3 thread_start + 15

Confirmation email found!
Extracted plain text part: Sign in to Undetectable AI.
https://undetectable.ai/api/auth/callback/sendgrid?callbackUrl=https%3A%2F%2Fundetectable.ai%2F&token=f509879000dbd60e9539b0261dbc38927df4f9ab3cf60f3c5f81548f0d6b46ae&email=craighe.artwe.ll%40gmail.com

Your OTP code is: 901781

**Comment by obaskly** [comment]
Hello
This is the wrong repo. Please check the correct one: https://github.com/obaskly/AiTextDetectionBypass
There is a new update.
